# Generated by Django 2.1.1 on 2018-09-14 14:48

import disasters.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField(default=0.5)),
                ('center_point', djongo.models.fields.EmbeddedModelField(model_container=disasters.models.GeoJSON, null=True)),
                ('level_of_danger', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('D', 'Danger'), ('ED', 'Extra Danger')], default='M', max_length=2)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
