# Generated by Django 2.1.1 on 2018-09-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
