# Generated by Django 2.1.1 on 2018-09-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0002_auto_20180914_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='lang',
            field=models.FloatField(default=50.3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disaster',
            name='lat',
            field=models.FloatField(default=22.6),
            preserve_default=False,
        ),
    ]
